version: '3.8'

services:
  api1:
    build:
      context: ./TISM_FIREBASE  # Caminho relativo para a pasta TISM_FIREBASE
      dockerfile: Dockerfile
    networks:
      - minha-rede
    ports:
      - "8080:8080"

  api2:
    build:
      context: ./TISM_MQTT  # Caminho relativo para a pasta TISM_MQTT
      dockerfile: Dockerfile
    networks:
      - minha-rede
    ports:
      - "8081:8080"

networks:
  minha-rede:
    driver: bridge
