name: appiot
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/uss_image.png
    - assets/images/ds_image.jpg
    - assets/images/motor_image.jpeg
    - assets/images/pump_image.jpg
    - assets/images/valve_image.jpeg
    - assets/images/ds_image.jpg
